name: Affiliate Azure App Config Deployment

on:
  workflow_dispatch:
    inputs:
      affiliate:
        description: 'Select the affiliate for Azure App Config Deploy'
        required: true
        type: choice
        options:
          - geisinger
          - cone
      environment:
        description: 'Select the environment for Azure App Config Deploy'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - uat
          - prod

jobs:
  deploy-azure-appconfig:
    runs-on: arc-org-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      - name: Determine App Configuration settings and import
        id: appconfig
        run: |
          case ${{ github.event.inputs.environment }} in
            "dev")
              echo "appconfig_endpoint=${{ secrets.NONPROD_APPCONFIG_ENDPOINT }}" >> $GITHUB_OUTPUT
              echo "label=${{ github.event.inputs.environment }}-${{ github.event.inputs.affiliate }}" >> $GITHUB_OUTPUT
              ;;
            "qa")
              echo "appconfig_endpoint=${{ secrets.NONPROD_APPCONFIG_ENDPOINT }}" >> $GITHUB_OUTPUT
              echo "label=${{ github.event.inputs.environment }}-${{ github.event.inputs.affiliate }}" >> $GITHUB_OUTPUT
              ;;
            "uat")
              echo "appconfig_endpoint=${{ secrets.NONPROD_APPCONFIG_ENDPOINT }}" >> $GITHUB_OUTPUT
              echo "label=${{ github.event.inputs.environment }}-${{ github.event.inputs.affiliate }}" >> $GITHUB_OUTPUT
              ;;
            "prod")
              echo "appconfig_endpoint=${{ secrets.PROD_APPCONFIG_ENDPOINT }}" >> $GITHUB_OUTPUT
              echo "label=${{ github.event.inputs.environment }}-${{ github.event.inputs.affiliate }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Import App Configuration
        run: |
          az appconfig kv import --endpoint ${{ steps.appconfig.outputs.appconfig_endpoint }} --auth-mode login -s file --path config/${{ github.event.inputs.affiliate }}/appconfig.yaml --format yaml --content-type application/yaml --label ${{ steps.appconfig.outputs.label }} --yes