name: Affiliate Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-org-runner-set
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_REGISTRY }}

      - name: Get branch name
        id: get_branch
        run: |
          echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Get short commit ID
        id: get_commit
        run: |
          SHORT_COMMIT_ID=$(git rev-parse --short HEAD)
          echo "SHORT_COMMIT_ID=$SHORT_COMMIT_ID" >> $GITHUB_ENV

      - name: Build, Tag, and Push Image to ACR
        run: |
          IMAGE_TAG=$(echo "$BRANCH" | cut -d'/' -f2)
          docker build -t ${{ secrets.ACR_REGISTRY }}.azurecr.io/azconfigdemo:$IMAGE_TAG .
          docker push ${{ secrets.ACR_REGISTRY }}.azurecr.io/azconfigdemo:$IMAGE_TAG